name: wasm-tests

on:
  push:
  pull_request:

jobs:
  test-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install micromamba and create wasm environment
        shell: bash -l {0}
        run: |
          curl -L https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
          eval "$(./bin/micromamba shell hook --shell bash)"
          export CONDA_SUBDIR=emscripten-wasm32
          micromamba create -n wasm-env \
              --platform=emscripten-wasm32 \
              -c https://repo.prefix.dev/emscripten-forge-4x\
              -c https://repo.prefix.dev/conda-forge \
              --yes \
              python numpy scipy matplotlib

      - name: Activate environment
        run: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate wasm-env
          python -V

      - name: Build wheel
        run: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate wasm-env
          pip wheel . -w dist

      - name: Install wheel
        run: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate wasm-env
          pip install dist/*.whl

      - name: Test installed package
        run: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate wasm-env
          pytest --pyargs your_package
